const phaseBase=phaseView,bagBase=()=>cleanText(bagView());
const TABS=['home','guide','bag','mine','urgent','p1','p2','p3','fix'];
const names={home:'เริ่มที่นี่',guide:'คู่มือรับมือ',bag:'เตรียมของ',mine:'รายการของฉัน',urgent:'น้ำกำลังเข้าบ้าน',p1:'ก่อนน้ำมา',p2:'ระหว่างน้ำท่วม',p3:'หลังน้ำลด',fix:'วิธีแก้ปัญหา'};
function heading(k,t,p){return `<div class="eyebrow">${k}</div><h1 class="lt">${t}</h1><p class="sub">${p}</p>`;}
function footerHTML(){return '<footer><b>Survival Kit</b><span>ซีรีส์ 01 · น้ำท่วม</span><p>รายการบันทึกในเบราว์เซอร์นี้เท่านั้น</p></footer>';}
function profileBlock(){return `<details class="profile-settings" id="profile-settings"><summary>บ้านและคนของคุณ <span>${S.kind==='house'?'บ้าน':'คอนโด'} · ${S.people} คน · แตะเพื่อปรับ</span></summary>${profileHTML()}</details>`;}
function nextBlock(title,description,tab,label){return `<section class="next-step"><div><span class="eyebrow">ขั้นต่อไป</span><h2>${title}</h2><p>${description}</p></div><button class="btn" data-go="${tab}">${label}</button></section>`;}
function sourceLibrary(){return SRC.map(s=>`<div class="srcrow"><div class="id">${s.id}</div><div><b>${s.t}</b><p class="n">${s.o}</p>${s.u?`<a target="_blank" rel="noopener noreferrer" href="${s.u}">เปิดแหล่งข้อมูล</a>`:'<p class="n">เอกสารอ้างอิงที่ไม่มีลิงก์ออนไลน์</p>'}</div></div>`).join('');}
homeView=function(){return heading('SURVIVAL SERIES 01 · น้ำท่วม','ตอนนี้คุณอยู่ในสถานการณ์ไหน?','เลือกสถานการณ์ แล้วเริ่มจากสิ่งที่สำคัญกับคุณตอนนี้')+`<div class="entry-grid">${[['before','01','เตรียมรับน้ำท่วม','ยังไม่ท่วม เริ่มเตรียมบ้าน คน และของ','list'],['enter','02','น้ำกำลังเข้าบ้าน','ดูสิ่งที่ต้องทำเร่งด่วนและขอความช่วยเหลือ','shield'],['in','03','อยู่ในพื้นที่น้ำท่วม','ดูแลน้ำ อาหาร สุขอนามัย และคนในบ้าน','drop'],['after','04','น้ำลดแล้ว','ตรวจความปลอดภัยก่อนกลับบ้านและฟื้นฟู','home']].map(x=>`<button class="entry ${x[0]}" data-s="${x[0]}"><div class="entry-art"><img src="assets/${x[0]}.webp" alt="" width="900" height="600" decoding="async"><span class="entry-number">${x[1]}</span></div><div class="entry-copy"><h2>${x[2]}</h2><p>${x[3]}</p><span class="entry-action">ดูสิ่งที่ควรทำ</span></div></button>`).join('')}</div><div class="safety-note">${icon('shield')}<p>หากไม่ปลอดภัย ให้ขอความช่วยเหลือทันที และทำตามประกาศของหน่วยงานในพื้นที่</p><button class="btn red" data-sos="1">เบอร์ฉุกเฉิน</button></div><div class="quick-path"><button data-go="bag">${icon('bag')} จัดกระเป๋าและของสำรอง</button><button data-go="mine">${icon('list')} กลับมาทำรายการต่อ</button></div>`+footerHTML();};
function guideView(){return heading('คู่มือรับมือ','เลือกอ่านเรื่องที่ต้องใช้','อ่านตามช่วงเวลา หรือเลือกปัญหาที่กำลังเจอ')+`<div class="guide-menu">${[['p1','01','ก่อนน้ำมา','เตรียมแผน บ้าน และคน'],['p2','02','ระหว่างน้ำท่วม','ใช้ชีวิตให้ปลอดภัย'],['p3','03','หลังน้ำลด','กลับบ้านและฟื้นฟู']].map(x=>`<button data-go="${x[0]}"><span>${x[1]}</span><div><h2>${x[2]}</h2><p>${x[3]}</p></div></button>`).join('')}</div><h2 class="section-title">หาคำตอบตามปัญหา</h2><div class="problem-grid">${FIX.map(f=>`<button data-fix="${f.id}">${icon(FIXI[f.id])}<span>${f.n}</span>${f.urgent?'<small>เร่งด่วน</small>':''}</button>`).join('')}</div><details class="reading-section"><summary>บทเรียนและเรื่องที่ควรรู้</summary>${LESSONS.map(lessonHTML).join('')}</details><details class="reading-section"><summary>แหล่งอ้างอิงทั้งหมด</summary>${sourceLibrary()}</details><p class="foot">คู่มือเพื่อเตรียมความพร้อมทั่วไป ให้ยึดประกาศหน่วยงานในพื้นที่สำหรับสถานการณ์จริง แหล่งอ้างอิงบางรายการเป็นเอกสารเก่า ควรตรวจคำแนะนำล่าสุดจากต้นทาง</p>`;}
rowHTML=function(i){const q=typeof i.q==='function'?i.q():i.q;if(i.kind==='guidance')return `<div class="task-row guidance-row"><span class="guidance-label">ข้อควรระวัง / คำแนะนำ</span><p class="task-text">${i.t}</p>${i.n?`<p class="n">${i.n}</p>`:''}${itemLink(i)}${chips(i.s)}</div>`;return `<div class="task-row"><label class="task-label"><input type="checkbox" data-id="${i.id}" ${S.done[i.id]?'checked':''}><span class="task-text">${i.t}</span></label>${i.n?`<p class="task-note">${i.n}</p>`:''}${q?`<span class="task-quantity">${q}</span>`:''}${itemLink(i)}${i.s?.length||i.u?`<details class="task-source"><summary>ที่มา${i.u?' / เหตุผลประกอบ':''}</summary>${chips(i.s,{u:i.u})}</details>`:''}</div>`;};
groupsHTML=function(items){const gs=[...new Set(items.map(i=>i.g))];return gs.map((g,n)=>{const a=items.filter(i=>i.g===g),tasks=a.filter(i=>i.kind!=='guidance');return `<details class="grp task-group" id="group-${hash(S.tab+g)}" ${n===0?'open':''}><summary class="gh"><b><span class="group-number">${String(n+1).padStart(2,'0')}</span>${g}</b><small>${tasks.length?tasks.filter(i=>S.done[i.id]).length+'/'+tasks.length+' งาน':'อ่านคำแนะนำ'}</small></summary><div class="card">${a.map(rowHTML).join('')}</div></details>`;}).join('');};
function scopedItems(){if(S.tab==='bag')return ITEMS.filter(i=>i.bag&&vis(i));if(['p1','p2','p3'].includes(S.tab))return list(+S.tab[1],i=>!i.bag&&i.kind!=='guidance');return [];}
function progressHTML(items){items=items.filter(i=>i.kind!=='guidance');const d=items.filter(i=>S.done[i.id]).length;return `<div class="local-progress"><span id="pgTxt">ทำแล้ว ${d} จาก ${items.length} ข้อ</span><div class="bar"><i id="pgBar" style="width:${items.length?d/items.length*100:0}%"></i></div><p>ความคืบหน้าของรายการนี้ ไม่ใช่คะแนนความปลอดภัย</p></div>`;}
function relatedHTML(ids){return `<h2 class="section-title">หากเจอปัญหานี้</h2><div class="related-links">${ids.map(id=>{const f=FIX.find(x=>x.id===id);return `<button data-fix="${id}">${icon(FIXI[id])}${f.n}</button>`;}).join('')}</div>`;}
phaseView=function(ph){const p=PH[ph],s={p1:'before',p2:'in',p3:'after'}[ph];let h=heading('คู่มือรับมือ · '+p.nm,p.h,p.p);h+=`<section class="first-actions"><h2>สิ่งสำคัญในช่วงนี้</h2><ol>${p.sum.slice(0,3).map(t=>`<li>${t}</li>`).join('')}</ol></section>`;h+=alternativesHTML(ph)+profileBlock()+`<h2 class="section-title">ค่อย ๆ ทำทีละหมวด</h2>`+progressHTML(list(+ph[1],i=>!i.bag))+groupsHTML(list(+ph[1],i=>!i.bag))+relatedHTML(SITS[s].fx);
 if(ph==='p3'){h+=`<details class="reading-section"><summary>อ่านเพิ่มเติม: วัสดุและการเฝ้าระวังสุขภาพ</summary>${phaseBase('p3').split('<section class="grp">').slice(1).map(x=>'<section class="grp">'+x).join('')}</details>`;}
 return h+(ph==='p1'?nextBlock('เตรียมของให้เหมาะกับบ้านคุณ','คำนวณของสำรองและแยกกระเป๋าฉุกเฉิน','bag','ไปเตรียมของ'):nextBlock('ดูรายการที่ยังเหลือ','กลับมาดูงานที่ทำแล้วและทำต่อทีละหมวด','mine','ดูรายการของฉัน'));};
function itemLink(i){return i.link?`<button class="btn soft sm item-link" ${i.link.fix?'data-fix="'+i.link.fix+'"':'data-go="'+i.link.tab+'"'}>${i.link.label}</button>`:'';}
function urgentView(){const f=FIX.find(f=>f.id==='enter');return heading('สถานการณ์เร่งด่วน','น้ำกำลังเข้าบ้าน','ให้ความปลอดภัยของคนมาก่อนการปกป้องทรัพย์สิน')+`<div class="safety-note"><p>หากติดอยู่หรือไม่ปลอดภัย โทร 1784 · ฉุกเฉินทางการแพทย์ โทร 1669</p><button class="btn red" data-sos="1">ขอความช่วยเหลือ</button></div><section class="urgent-steps"><h2>คนปลอดภัยก่อน แล้วค่อยดูแลทรัพย์สิน</h2><ol class="steps">${f.st.map(s=>`<li>${s[0]}${s[3]?`<p class="n">${s[3]}</p>`:''}${chips(s[1])}</li>`).join('')}</ol>${f.dont?.length?`<div class="dont"><h3>อย่าทำ</h3><ul>${f.dont.map(x=>`<li>${x}</li>`).join('')}</ul></div>`:''}</section>`+relatedHTML(['elec','leave','stuck'])+nextBlock('หากยังอยู่ในพื้นที่น้ำท่วม','อ่านเรื่องน้ำ อาหาร และสุขอนามัย','p2','ดูคู่มือระหว่างท่วม');}
function kitView(){return `<section class="kit-intro"><div>${heading('เตรียมของ','พร้อมหยิบ พร้อมไป','จัดกระเป๋าฉุกเฉินและของสำรองให้พอดีกับคนในบ้าน')}</div><img src="assets/kit.webp" width="900" height="600" alt="ภาพประกอบกระเป๋าฉุกเฉินและอุปกรณ์จำเป็น" decoding="async"></section>`+profileBlock()+alternativesHTML('bag')+progressHTML(ITEMS.filter(i=>i.bag&&vis(i)))+bagBase()+nextBlock('เช็กสิ่งที่ยังเหลือ','ดูความคืบหน้าแยกตามรายการ','mine','ดูรายการของฉัน');}
function mineView(){const sets=[['p1','เตรียมก่อนน้ำมา',ITEMS.filter(i=>i.ph===1&&!i.bag&&i.kind!=='guidance'&&vis(i))],['bag','กระเป๋าและของสำรอง',ITEMS.filter(i=>i.bag&&vis(i))],['p2','ระหว่างน้ำท่วม',ITEMS.filter(i=>i.ph===2&&!i.bag&&i.kind!=='guidance'&&vis(i))],['p3','หลังน้ำลด',ITEMS.filter(i=>i.ph===3&&!i.bag&&i.kind!=='guidance'&&vis(i))]];return heading('รายการของฉัน','กลับมาทำต่อได้ตรงนี้','ดูความคืบหน้าแยกตามช่วง เลือกเฉพาะรายการที่เกี่ยวกับคุณตอนนี้')+profileBlock()+`<div class="my-lists">${sets.map(([tab,title,items])=>{const d=items.filter(i=>S.done[i.id]).length;return `<article><h2>${title}</h2><p>ทำแล้ว ${d} / ${items.length} ข้อ</p><div class="bar"><i style="width:${items.length?100*d/items.length:0}%"></i></div><p class="n">${items.length-d?'ยังเหลือ '+(items.length-d)+' ข้อ':'ครบรายการแล้ว'}</p><button class="btn" data-go="${tab}">เปิดรายการ</button></article>`;}).join('')}</div><details class="reading-section"><summary>ตรวจอุปกรณ์ประจำปี</summary>${kitHTML()}</details><details class="reading-section"><summary>จัดการข้อมูลที่บันทึก</summary><p class="n">ข้อมูลเก็บในเบราว์เซอร์นี้ หากล้างข้อมูลเบราว์เซอร์หรือเปลี่ยนเครื่อง รายการจะไม่ตามไปด้วย</p><div id="resetBox"><button class="btn line" id="resetBtn">ล้างข้อมูลที่ติ๊กไว้</button></div></details>`;}
render=function(){const openIds=[...document.querySelectorAll('details[id][open]')].map(x=>x.id);document.body.dataset.tab=S.tab;const active=['p1','p2','p3','fix','urgent'].includes(S.tab)?'guide':S.tab;document.querySelectorAll('.tab').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.t===active));b.setAttribute('aria-current',b.dataset.t===active?'page':'false');});const v=$('view');v.style.zoom=S.z;$('zBtn').textContent=S.z===1?'Aa':S.z===1.15?'Aa+':'Aa++';const html=S.tab==='home'?homeView():S.tab==='guide'?guideView():S.tab==='bag'?kitView():S.tab==='mine'?mineView():S.tab==='urgent'?urgentView():S.tab==='fix'?fixView():phaseView(S.tab);v.innerHTML=`<div class="view flow-view">${!['home','guide','bag','mine'].includes(S.tab)?'<button class="back-link" data-go="guide">กลับไปเลือกหัวข้อ</button>':''}${cleanText(html)}</div>`;openIds.forEach(id=>{const e=$(id);if(e)e.open=true;});save();};
go=function(tab,top){history.replaceState({tab:S.tab,y:window.scrollY},'',location.href);S.tab=tab;history.pushState({tab,y:0},'','#'+tab);render();if(top!==false){window.scrollTo({top:0});$('view').focus({preventScroll:true});}};
window.addEventListener('popstate',e=>{const tab=location.hash.slice(1);S.tab=TABS.includes(tab)?tab:'home';render();window.scrollTo({top:e.state?.y||0});});
updateProgressUI=function(){const a=scopedItems(),d=a.filter(i=>S.done[i.id]).length;if($('pgBar'))$('pgBar').style.width=(a.length?100*d/a.length:0)+'%';if($('pgTxt'))$('pgTxt').textContent=`ทำแล้ว ${d} จาก ${a.length} ข้อ`;};
$('bd').addEventListener('click',()=>{document.body.style.overflow='';sheetTrigger?.focus();});
const initial=location.hash.slice(1);S.tab=TABS.includes(initial)?initial:'home';history.replaceState({tab:S.tab,y:0},'','#'+S.tab);render();
